[package]
name = "kassa-lt"
version = "1.0.0"
description = "Kassa-LT packaged using Tauri"
authors = ["Stebf"]
license = "BSD-3-Clause license"
repository = "https://github.com/Stebf/kassa-lt"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = 2 # Optimizer
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
log = "0.4"
tauri = { version = "2.11.2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-log = "2"
tauri-plugin-store = "2.0.0"
rusqlite = { version = "0.40", features = ["bundled", "backup"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
r2d2 = "0.8"
csv = "1.4.0"
once_cell = "1.21.4"
env_logger = "0.11.10"
reqwest_dav = "0.3.3"
tauri-plugin-http = "2"

[dev-dependencies]
tempfile = "3"
